sudo: required

services:
  - docker

cache: 
  directories:
    - $HOME/.cache/docker-tectonic

before_script:
  - mkdir -p $HOME/.cache/docker-tectonic out
  - chmod 0777 .
  - chmod 0777 out
  - chmod 0777 $HOME/.cache/docker-tectonic

script:
  - sudo docker run -ti --rm --volume $HOME/.cache/docker-tectonic:/home/tectonic/.cache:z --volume `pwd`:/tectonic:z fabianhauser/tectonic CV.tex --outdir out

before_cache:
  - chmod 0777 $HOME/.cache/docker-tectonic -R

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: out
  on:
    branch: master