sudo: required

services:
  - docker

cache:
  directories:
  - $HOME/.cache/docker-tectonic

before_script:
  - make create_out_dir
  # We need 0777 for these folders because tectonic runs under the user 'tectonic' in the docker container.
  - chmod 0777 $HOME/.cache/docker-tectonic out

script: make CV

notifications:
  email:
    on_success: never
    on_failure: change

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: out
  on:
    branch: master
